Repository D-PRlME/Togather-Server, pull requests merged in 2022-09, with the labels that each got.

#54 ⚡ :: 아이디 찾기 삭제, 이메일 수정
  src/main/java/com/project/draw/domain/user/domain/User.java
  src/main/java/com/project/draw/domain/user/presentation/UserController.java
  src/main/java/com/project/draw/domain/user/presentation/dto/request/UpdateEmailRequest.java
  src/main/java/com/project/draw/domain/user/presentation/dto/response/QueryUserInfoResponse.java
  src/main/java/com/project/draw/domain/user/service/QueryMyInfoService.java
  src/main/java/com/project/draw/domain/user/service/QueryUserInfoService.java
  src/main/java/com/project/draw/domain/user/service/UpdateEmailService.java
Labels: 기능추가

#55 ♻️ :: (#52) getById()로 메소드명 수정
  src/main/java/com/project/draw/domain/post/facade/PostFacade.java
  src/main/java/com/project/draw/domain/post/service/DeletePostService.java
  src/main/java/com/project/draw/domain/post/service/QueryPostInfoService.java
  src/main/java/com/project/draw/domain/post/service/UpdatePostService.java
Labels: 리팩토링

#64 ♻️ :: (#61) 기타 리팩토링
  src/main/java/com/project/draw/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/com/project/draw/domain/user/domain/User.java
  src/main/java/com/project/draw/domain/user/facade/UserFacade.java
  src/main/java/com/project/draw/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/com/project/draw/domain/user/service/LogoutService.java
  src/main/java/com/project/draw/domain/user/service/SendSignupAuthCodeService.java
  src/main/java/com/project/draw/domain/user/service/SignupService.java
Labels: 리팩토링

#65 ✨ :: (#56) 게시글 검색 Api 구현
  src/main/java/com/project/draw/domain/post/domain/repository/PostRepository.java
  src/main/java/com/project/draw/domain/post/presentation/PostController.java
  src/main/java/com/project/draw/domain/post/service/QueryPostByKeywordService.java
Labels: 기능추가

#67 ✨ :: (#66) 구글 로그인 Api 추가
  build.gradle
  src/main/java/com/project/draw/domain/auth/presentation/GoogleController.java
  src/main/java/com/project/draw/domain/auth/service/GoogleAuthService.java
  src/main/java/com/project/draw/global/error/exception/ErrorCode.java
  src/main/java/com/project/draw/global/properties/AuthProperties.java
  src/main/java/com/project/draw/global/util/auth/service/QueryGoogleAuthLinkService.java
  src/main/java/com/project/draw/infrastructure/feign/FeignClientErrorDecoder.java
  src/main/java/com/project/draw/infrastructure/feign/FeignConfig.java
  src/main/java/com/project/draw/infrastructure/feign/client/GoogleAuth.java
  src/main/java/com/project/draw/infrastructure/feign/client/GoogleInfo.java
  src/main/java/com/project/draw/infrastructure/feign/dto/request/CodeRequest.java
  src/main/java/com/project/draw/infrastructure/feign/dto/request/GoogleCodeRequest.java
  src/main/java/com/project/draw/infrastructure/feign/dto/response/GoogleInfoResponse.java
  src/main/java/com/project/draw/infrastructure/feign/dto/response/TokenResponse.java
  src/main/java/com/project/draw/infrastructure/feign/exception/OtherBadRequestException.java
  src/main/java/com/project/draw/infrastructure/feign/exception/OtherExpiredTokenException.java
  src/main/java/com/project/draw/infrastructure/feign/exception/OtherForbiddenException.java
  src/main/java/com/project/draw/infrastructure/feign/exception/OtherUnAuthorizedException.java
  src/main/resources/application.yml
Labels: 기능추가

#73 🔀 :: (#71) postBuilder 중복코드
  src/main/java/com/project/draw/domain/post/presentation/dto/response/.gitkeep
  src/main/java/com/project/draw/domain/post/presentation/dto/response/PostListResponse.java
  src/main/java/com/project/draw/domain/post/presentation/dto/response/PostResponse.java
  src/main/java/com/project/draw/domain/post/service/CreatePostService.java
  src/main/java/com/project/draw/domain/post/service/QueryMyPostService.java
  src/main/java/com/project/draw/domain/post/service/QueryPostByKeywordService.java
  src/main/java/com/project/draw/domain/post/service/QueryPostByTagService.java
  src/main/java/com/project/draw/domain/post/service/QueryPostsService.java
Labels: 리팩토링

#85 🔀 :: Tag 리스트 조회 Api 구현
  build.gradle
  src/main/java/com/project/draw/domain/post/domain/Tag.java
  src/main/java/com/project/draw/domain/post/presentation/PostController.java
  src/main/java/com/project/draw/domain/post/presentation/dto/response/TagListResponse.java
  src/main/java/com/project/draw/domain/post/service/QueryTagsService.java
  src/main/resources/application.yml
Labels: 기능추가

#94 ♻️ :: (#91) 인가 범위, config 방식 수정
  src/main/java/com/project/draw/global/security/SecurityConfig.java
Labels: 리팩토링

#98 🔀 :: (#97) Post 등록 시간 포맷팅
  src/main/java/com/project/draw/domain/auth/service/GoogleAuthService.java
  src/main/java/com/project/draw/domain/post/presentation/dto/response/PostInfoResponse.java
  src/main/java/com/project/draw/domain/post/presentation/dto/response/PostResponse.java
  src/main/java/com/project/draw/domain/post/service/QueryPostInfoService.java
  src/main/java/com/project/draw/global/security/AuthProperties.java
  src/main/java/com/project/draw/global/util/auth/service/QueryGoogleAuthLinkService.java
  src/main/java/com/project/draw/global/util/date/DateUtil.java
Labels: 기능추가

#113 ⚡ :: (#112)SonarCloud 추가
  .github/workflow/ci.yml
  build.gradle
Labels: 기능추가

#121 🔀 :: (#119) 프로젝트 생성, 초대 기능 구현
  Dockerfile
  README.md
  src/main/java/com/project/draw/domain/chat/domain/Room.java
  src/main/java/com/project/draw/domain/post/domain/repository/PostRepository.java
  src/main/java/com/project/draw/domain/post/service/QueryPostsByKeywordService.java
  src/main/java/com/project/draw/domain/post/service/QueryPostsByTagService.java
  src/main/java/com/project/draw/domain/project/domain/Project.java
  src/main/java/com/project/draw/domain/project/presentation/dto/request/AcceptInviteRequest.java
  src/main/java/com/project/draw/domain/project/presentation/dto/request/CreateProjectRequest.java
  src/main/java/com/project/draw/domain/project/presentation/dto/response/CreateProjectResponse.java
  src/main/java/com/project/draw/domain/project/presentation/dto/response/QueryProjectInfoResponse.java
  src/main/java/com/project/draw/domain/project/service/AcceptInviteService.java
  src/main/java/com/project/draw/domain/project/service/CreateProjectService.java
  src/main/java/com/project/draw/domain/project/service/InviteUserService.java
  src/main/java/com/project/draw/domain/user/domain/User.java
  src/main/java/com/project/draw/domain/user/service/SignupService.java
Labels: 기능추가

#125 🔀 :: (#117) CI/CD 구축
  .github/workflow/CD.yml
  .github/workflow/CI.yml
Labels: chore

#127 ⚡ :: 유저 프로필 정보 수정
  src/main/java/com/project/draw/domain/post/domain/Like.java
  src/main/java/com/project/draw/domain/post/domain/Post.java
  src/main/java/com/project/draw/domain/post/domain/repository/LikeRepository.java
  src/main/java/com/project/draw/domain/post/facade/LikeFacade.java
  src/main/java/com/project/draw/domain/post/presentation/LikeController.java
  src/main/java/com/project/draw/domain/post/presentation/PostController.java
  src/main/java/com/project/draw/domain/post/presentation/dto/response/PostInfoResponse.java
  src/main/java/com/project/draw/domain/post/presentation/dto/response/PostResponse.java
  src/main/java/com/project/draw/domain/post/service/DeletePostService.java
  src/main/java/com/project/draw/domain/post/service/QueryMyPostService.java
  src/main/java/com/project/draw/domain/post/service/QueryPostsByKeywordService.java
  src/main/java/com/project/draw/domain/post/service/QueryPostsByTagService.java
  src/main/java/com/project/draw/domain/post/service/QueryPostsInfoService.java
  src/main/java/com/project/draw/domain/user/domain/Position.java
  src/main/java/com/project/draw/domain/user/domain/User.java
  src/main/java/com/project/draw/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/com/project/draw/domain/user/presentation/dto/response/QueryUserInfoResponse.java
  src/main/java/com/project/draw/domain/user/service/QueryMyInfoService.java
  src/main/java/com/project/draw/domain/user/service/QueryUserInfoService.java
Labels: 기능추가

#137 🔀 :: (#136) 테스트코드 수정
  src/test/java/com/project/draw/domain/FailTest.java
  src/test/java/com/project/draw/domain/chat/service/SendChatServiceTest.java
  src/test/java/com/project/draw/domain/project/service/AcceptInviteServiceTest.java
Labels: 테스트

#141 📝 :: (#140)LICENSE 추가
  LICENSE
Labels: DOCS
